
name: To operate functions

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  [push , pull_reuest]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  job1 :
    name: Addition Function
# The type of runner that the job will run on
    runs-on: ubuntu-16.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Addition of 2 and 4
        shell: bash
        run: |
          expr 2 + 4 > AddBook.txt
      - name  : upload AddResults for job1
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        uses: actions/upload-artifact@v2
        with :
          name: Book1
          path : AddBook.txt 
              
